# This workflow triggers a build of the production docs site

name: Build Production Site

on:
  push:
    branches: [ main, 'v/*' ]

jobs:
  dispatch:
    runs-on: ubuntu-latest
    steps:
    - name: Trigger build
      run: curl -X POST -d {} https://api.netlify.com/build_hooks/649c07c466bddd0764936773
